### ISSUE TITLE
document.ready?

### ISSUE THREAD

**Issue by augustogoncalves** [libvarun/forge-extensions#10]
shouldn't this be inside the document ready event? may fail on slow connection... 

https://github.com/libvarun/StandardExtensions/blob/master/public/StandardExtensions/extensionloader.js#L3

**Comment by libvarun** [comment]
list is created after model is loaded in the viewer, so it won't be a problem.
https://github.com/libvarun/StandardExtensions/blob/master/public/StandardExtensions/extensionloader.js#L20

**Comment by augustogoncalves** [comment]
right, but in this case the loadJSON is called on the beginning, while the method is only defined in the end. in case of a very slow connection, you may get a "method undefined" error.

**Comment by libvarun** [comment]
done.
