### ISSUE TITLE
Config duplication

### ISSUE THREAD

**Issue by apprentice3d** [libvarun/forge-extensions#11]
When creating a new extensions, there is **_internal config_** 
(g.e. `public/extensions/BasicSkeleton/config.json`) 
and there is **_aggregated config_** 
`public/extensions/config.json`, which has **Extension** array with content of those **_internal configs_**.

The **_internal config_** seems to be redundant, yet its content is important.
The current process of adding a new extension is to add a folder, write the config, then copy the content of **_internal config_** content into the **Extension** part of the **_aggregated config_**

Perhaps a better approach would be that upon server starting, to autofill the **Extension** part of the **_aggregated config_** , by traversing the content of `public/extensions` subfolders and insert into **Extension** array the content of each config.

Thus, the process of adding a new extension would be just to add a folder with presented structure and have the config in that folder.

**Comment by libvarun** [comment]
Thanks.

Need to figure out external dependency management to avoid duplicates(in case 2 or more extensions require same resource like jquery), currently it's done manually, so your suggestion is good option.

Probably this redundancy needs to be explained better in note in the beginning or your idea will be implemented.

**Comment by augustogoncalves** [comment]
avoiding duplicated information is important, also important to make sure whatever is needed for an extension is encapsulated on its folder (not outside), so traversing the extensions folder to collect information can fix that. 

we control the extensions, but if a developer downloads 1 extension, they should know all they need to run it (therefore the config.json per extension + readme)

**Comment by libvarun** [comment]
done.
