### ISSUE TITLE
suggestions for NestedViewerExtension

### ISSUE THREAD

**Issue by augustogoncalves** [libvarun/forge-extensions#14]
nice work @petrbroz !

can we add: 
1. readme on the extension folder (general how the code works, limitations, author, etc.)
2. link to it from the app (see #2 @libvarun )

and maybe add (not major)
1. resizable?
2. toolbar button with push style (on/off)

some expected behavior (from other samples):
1. click on the nested, highlight/select on the main? (and vice-versa)
2. option on the config.json to show only 2D (or only 3D)?

**Comment by petrbroz** [comment]
Sounds good. Let me look into that.

**Comment by petrbroz** [comment]
All of the suggestions above are addressed in https://github.com/libvarun/forge-extensions/pull/15.

**Comment by augustogoncalves** [comment]
it seems the `select` is inheriting the text color from bootstrap, therefore white over white

![image](https://user-images.githubusercontent.com/4291593/78307656-41562780-74fb-11ea-82b6-30f4854d7606.png)

**Comment by petrbroz** [comment]
Thanks, I'll fix that.

**Comment by petrbroz** [comment]
https://github.com/libvarun/forge-extensions/pull/17
