### ISSUE TITLE
persistent vs transient buckets

### ISSUE THREAD

**Issue by augustogoncalves** [libvarun/forge-extensions#3]
let's make 1 bucket persistent with a few sample files (1 of each kind/industry), we can collect them later. Block upload on this bucket (client & server)

and 1 bucket transient where users can upload files, and consider adding a delete right-click menu.

![image](https://user-images.githubusercontent.com/4291593/75383398-1ee44500-5891-11ea-86d1-e2ec5ce14657.png)

**Comment by augustogoncalves** [comment]
let's also rename "buckets & objects" to something else, like "sample models"

**Comment by libvarun** [comment]
fixed
