### ISSUE TITLE
callback URL

### ISSUE THREAD

**Issue by augustogoncalves** [libvarun/forge-extensions#8]
for consistency with other samples, let's use PORT 3000 at readme>setup

**Comment by libvarun** [comment]
most of our projects run on 3000, when a developer wants to run 2 or more projects locally, they need to change the port number manually, do you still prefer it to be changed to 3000?

**Comment by augustogoncalves** [comment]
yes, all samples should run the same way (same env vars, ports, and a basic setup as similar as possible)

**Comment by libvarun** [comment]
done.
