### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by augustogoncalves** [libvarun/forge-extensions#9]
- add a section with list of extensions (for now, just "transform")
- add a thumbnail image (must be thumbnail.png or .gif at the root folder)
- setup section should be how to run it locally (this is there, but at the bottom, just a matter of organizing it) 
- add a section for "how to add new extensions"

the "Understanding extensionloader..." section is good, nice work

**Comment by libvarun** [comment]
"how to add new extensions" is already there
https://github.com/libvarun/StandardExtensions#steps-to-plug-in-new-extension

**Comment by libvarun** [comment]
setup rearranging is done.

**Comment by libvarun** [comment]
all done, please take a look if everything is fine.
